// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddContactNotice.proto

package com.tingyu.venus.netty.protobuf;

public final class ContactAddNotice {
  private ContactAddNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactAddNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ContactAddNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发起方手机号
     * </pre>
     *
     * <code>string fromPhone = 1;</code>
     * @return The fromPhone.
     */
    java.lang.String getFromPhone();
    /**
     * <pre>
     *发起方手机号
     * </pre>
     *
     * <code>string fromPhone = 1;</code>
     * @return The bytes for fromPhone.
     */
    com.google.protobuf.ByteString
        getFromPhoneBytes();

    /**
     * <pre>
     *发起用户名
     * </pre>
     *
     * <code>string fromName = 2;</code>
     * @return The fromName.
     */
    java.lang.String getFromName();
    /**
     * <pre>
     *发起用户名
     * </pre>
     *
     * <code>string fromName = 2;</code>
     * @return The bytes for fromName.
     */
    com.google.protobuf.ByteString
        getFromNameBytes();

    /**
     * <pre>
     *发起方头像
     * </pre>
     *
     * <code>string fromAvatar = 3;</code>
     * @return The fromAvatar.
     */
    java.lang.String getFromAvatar();
    /**
     * <pre>
     *发起方头像
     * </pre>
     *
     * <code>string fromAvatar = 3;</code>
     * @return The bytes for fromAvatar.
     */
    com.google.protobuf.ByteString
        getFromAvatarBytes();

    /**
     * <pre>
     *接收方方手机号
     * </pre>
     *
     * <code>string toPhone = 4;</code>
     * @return The toPhone.
     */
    java.lang.String getToPhone();
    /**
     * <pre>
     *接收方方手机号
     * </pre>
     *
     * <code>string toPhone = 4;</code>
     * @return The bytes for toPhone.
     */
    com.google.protobuf.ByteString
        getToPhoneBytes();

    /**
     * <pre>
     *接收方用户名
     * </pre>
     *
     * <code>string toName = 5;</code>
     * @return The toName.
     */
    java.lang.String getToName();
    /**
     * <pre>
     *接收方用户名
     * </pre>
     *
     * <code>string toName = 5;</code>
     * @return The bytes for toName.
     */
    com.google.protobuf.ByteString
        getToNameBytes();

    /**
     * <pre>
     *接收方方头像
     * </pre>
     *
     * <code>string toAvatar = 6;</code>
     * @return The toAvatar.
     */
    java.lang.String getToAvatar();
    /**
     * <pre>
     *接收方方头像
     * </pre>
     *
     * <code>string toAvatar = 6;</code>
     * @return The bytes for toAvatar.
     */
    com.google.protobuf.ByteString
        getToAvatarBytes();

    /**
     * <pre>
     *添加原因
     * </pre>
     *
     * <code>string reason = 7;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <pre>
     *添加原因
     * </pre>
     *
     * <code>string reason = 7;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();

    /**
     * <pre>
     *邀请状态，新的邀请，邀请被接收，邀请被拒绝
     * </pre>
     *
     * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <pre>
     *邀请状态，新的邀请，邀请被接收，邀请被拒绝
     * </pre>
     *
     * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
     * @return The status.
     */
    com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus getStatus();
  }
  /**
   * Protobuf type {@code ContactAddNoticeMessage}
   */
  public static final class ContactAddNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ContactAddNoticeMessage)
      ContactAddNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactAddNoticeMessage.newBuilder() to construct.
    private ContactAddNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactAddNoticeMessage() {
      fromPhone_ = "";
      fromName_ = "";
      fromAvatar_ = "";
      toPhone_ = "";
      toName_ = "";
      toAvatar_ = "";
      reason_ = "";
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContactAddNoticeMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactAddNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fromPhone_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fromName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fromAvatar_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              toPhone_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              toName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              toAvatar_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tingyu.venus.netty.protobuf.ContactAddNotice.internal_static_ContactAddNoticeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tingyu.venus.netty.protobuf.ContactAddNotice.internal_static_ContactAddNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.class, com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code ContactAddNoticeMessage.InvitationStatus}
     */
    public enum InvitationStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INVITE_NEW = 0;</code>
       */
      INVITE_NEW(0),
      /**
       * <code>INVITE_ACCEPT = 1;</code>
       */
      INVITE_ACCEPT(1),
      /**
       * <code>INVITE_REJECT = 2;</code>
       */
      INVITE_REJECT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>INVITE_NEW = 0;</code>
       */
      public static final int INVITE_NEW_VALUE = 0;
      /**
       * <code>INVITE_ACCEPT = 1;</code>
       */
      public static final int INVITE_ACCEPT_VALUE = 1;
      /**
       * <code>INVITE_REJECT = 2;</code>
       */
      public static final int INVITE_REJECT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InvitationStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static InvitationStatus forNumber(int value) {
        switch (value) {
          case 0: return INVITE_NEW;
          case 1: return INVITE_ACCEPT;
          case 2: return INVITE_REJECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<InvitationStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          InvitationStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InvitationStatus>() {
              public InvitationStatus findValueByNumber(int number) {
                return InvitationStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final InvitationStatus[] VALUES = values();

      public static InvitationStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private InvitationStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ContactAddNoticeMessage.InvitationStatus)
    }

    public static final int FROMPHONE_FIELD_NUMBER = 1;
    private volatile java.lang.Object fromPhone_;
    /**
     * <pre>
     *发起方手机号
     * </pre>
     *
     * <code>string fromPhone = 1;</code>
     * @return The fromPhone.
     */
    @java.lang.Override
    public java.lang.String getFromPhone() {
      java.lang.Object ref = fromPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromPhone_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发起方手机号
     * </pre>
     *
     * <code>string fromPhone = 1;</code>
     * @return The bytes for fromPhone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromPhoneBytes() {
      java.lang.Object ref = fromPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object fromName_;
    /**
     * <pre>
     *发起用户名
     * </pre>
     *
     * <code>string fromName = 2;</code>
     * @return The fromName.
     */
    @java.lang.Override
    public java.lang.String getFromName() {
      java.lang.Object ref = fromName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发起用户名
     * </pre>
     *
     * <code>string fromName = 2;</code>
     * @return The bytes for fromName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromNameBytes() {
      java.lang.Object ref = fromName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMAVATAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object fromAvatar_;
    /**
     * <pre>
     *发起方头像
     * </pre>
     *
     * <code>string fromAvatar = 3;</code>
     * @return The fromAvatar.
     */
    @java.lang.Override
    public java.lang.String getFromAvatar() {
      java.lang.Object ref = fromAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAvatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发起方头像
     * </pre>
     *
     * <code>string fromAvatar = 3;</code>
     * @return The bytes for fromAvatar.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromAvatarBytes() {
      java.lang.Object ref = fromAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPHONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object toPhone_;
    /**
     * <pre>
     *接收方方手机号
     * </pre>
     *
     * <code>string toPhone = 4;</code>
     * @return The toPhone.
     */
    @java.lang.Override
    public java.lang.String getToPhone() {
      java.lang.Object ref = toPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toPhone_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收方方手机号
     * </pre>
     *
     * <code>string toPhone = 4;</code>
     * @return The bytes for toPhone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToPhoneBytes() {
      java.lang.Object ref = toPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TONAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object toName_;
    /**
     * <pre>
     *接收方用户名
     * </pre>
     *
     * <code>string toName = 5;</code>
     * @return The toName.
     */
    @java.lang.Override
    public java.lang.String getToName() {
      java.lang.Object ref = toName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收方用户名
     * </pre>
     *
     * <code>string toName = 5;</code>
     * @return The bytes for toName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToNameBytes() {
      java.lang.Object ref = toName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOAVATAR_FIELD_NUMBER = 6;
    private volatile java.lang.Object toAvatar_;
    /**
     * <pre>
     *接收方方头像
     * </pre>
     *
     * <code>string toAvatar = 6;</code>
     * @return The toAvatar.
     */
    @java.lang.Override
    public java.lang.String getToAvatar() {
      java.lang.Object ref = toAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAvatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收方方头像
     * </pre>
     *
     * <code>string toAvatar = 6;</code>
     * @return The bytes for toAvatar.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToAvatarBytes() {
      java.lang.Object ref = toAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FIELD_NUMBER = 7;
    private volatile java.lang.Object reason_;
    /**
     * <pre>
     *添加原因
     * </pre>
     *
     * <code>string reason = 7;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *添加原因
     * </pre>
     *
     * <code>string reason = 7;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <pre>
     *邀请状态，新的邀请，邀请被接收，邀请被拒绝
     * </pre>
     *
     * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     *邀请状态，新的邀请，邀请被接收，邀请被拒绝
     * </pre>
     *
     * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
     * @return The status.
     */
    @java.lang.Override public com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus result = com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus.valueOf(status_);
      return result == null ? com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFromPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromPhone_);
      }
      if (!getFromNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fromName_);
      }
      if (!getFromAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromAvatar_);
      }
      if (!getToPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toPhone_);
      }
      if (!getToNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, toName_);
      }
      if (!getToAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, toAvatar_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, reason_);
      }
      if (status_ != com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus.INVITE_NEW.getNumber()) {
        output.writeEnum(8, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromPhone_);
      }
      if (!getFromNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fromName_);
      }
      if (!getFromAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromAvatar_);
      }
      if (!getToPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toPhone_);
      }
      if (!getToNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, toName_);
      }
      if (!getToAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, toAvatar_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, reason_);
      }
      if (status_ != com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus.INVITE_NEW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage)) {
        return super.equals(obj);
      }
      com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage other = (com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage) obj;

      if (!getFromPhone()
          .equals(other.getFromPhone())) return false;
      if (!getFromName()
          .equals(other.getFromName())) return false;
      if (!getFromAvatar()
          .equals(other.getFromAvatar())) return false;
      if (!getToPhone()
          .equals(other.getToPhone())) return false;
      if (!getToName()
          .equals(other.getToName())) return false;
      if (!getToAvatar()
          .equals(other.getToAvatar())) return false;
      if (!getReason()
          .equals(other.getReason())) return false;
      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getFromPhone().hashCode();
      hash = (37 * hash) + FROMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFromName().hashCode();
      hash = (37 * hash) + FROMAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getFromAvatar().hashCode();
      hash = (37 * hash) + TOPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getToPhone().hashCode();
      hash = (37 * hash) + TONAME_FIELD_NUMBER;
      hash = (53 * hash) + getToName().hashCode();
      hash = (37 * hash) + TOAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getToAvatar().hashCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ContactAddNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ContactAddNoticeMessage)
        com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tingyu.venus.netty.protobuf.ContactAddNotice.internal_static_ContactAddNoticeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tingyu.venus.netty.protobuf.ContactAddNotice.internal_static_ContactAddNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.class, com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.Builder.class);
      }

      // Construct using com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromPhone_ = "";

        fromName_ = "";

        fromAvatar_ = "";

        toPhone_ = "";

        toName_ = "";

        toAvatar_ = "";

        reason_ = "";

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tingyu.venus.netty.protobuf.ContactAddNotice.internal_static_ContactAddNoticeMessage_descriptor;
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage getDefaultInstanceForType() {
        return com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage build() {
        com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage buildPartial() {
        com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage result = new com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage(this);
        result.fromPhone_ = fromPhone_;
        result.fromName_ = fromName_;
        result.fromAvatar_ = fromAvatar_;
        result.toPhone_ = toPhone_;
        result.toName_ = toName_;
        result.toAvatar_ = toAvatar_;
        result.reason_ = reason_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage) {
          return mergeFrom((com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage other) {
        if (other == com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.getDefaultInstance()) return this;
        if (!other.getFromPhone().isEmpty()) {
          fromPhone_ = other.fromPhone_;
          onChanged();
        }
        if (!other.getFromName().isEmpty()) {
          fromName_ = other.fromName_;
          onChanged();
        }
        if (!other.getFromAvatar().isEmpty()) {
          fromAvatar_ = other.fromAvatar_;
          onChanged();
        }
        if (!other.getToPhone().isEmpty()) {
          toPhone_ = other.toPhone_;
          onChanged();
        }
        if (!other.getToName().isEmpty()) {
          toName_ = other.toName_;
          onChanged();
        }
        if (!other.getToAvatar().isEmpty()) {
          toAvatar_ = other.toAvatar_;
          onChanged();
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fromPhone_ = "";
      /**
       * <pre>
       *发起方手机号
       * </pre>
       *
       * <code>string fromPhone = 1;</code>
       * @return The fromPhone.
       */
      public java.lang.String getFromPhone() {
        java.lang.Object ref = fromPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发起方手机号
       * </pre>
       *
       * <code>string fromPhone = 1;</code>
       * @return The bytes for fromPhone.
       */
      public com.google.protobuf.ByteString
          getFromPhoneBytes() {
        java.lang.Object ref = fromPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发起方手机号
       * </pre>
       *
       * <code>string fromPhone = 1;</code>
       * @param value The fromPhone to set.
       * @return This builder for chaining.
       */
      public Builder setFromPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发起方手机号
       * </pre>
       *
       * <code>string fromPhone = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromPhone() {
        
        fromPhone_ = getDefaultInstance().getFromPhone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发起方手机号
       * </pre>
       *
       * <code>string fromPhone = 1;</code>
       * @param value The bytes for fromPhone to set.
       * @return This builder for chaining.
       */
      public Builder setFromPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromName_ = "";
      /**
       * <pre>
       *发起用户名
       * </pre>
       *
       * <code>string fromName = 2;</code>
       * @return The fromName.
       */
      public java.lang.String getFromName() {
        java.lang.Object ref = fromName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发起用户名
       * </pre>
       *
       * <code>string fromName = 2;</code>
       * @return The bytes for fromName.
       */
      public com.google.protobuf.ByteString
          getFromNameBytes() {
        java.lang.Object ref = fromName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发起用户名
       * </pre>
       *
       * <code>string fromName = 2;</code>
       * @param value The fromName to set.
       * @return This builder for chaining.
       */
      public Builder setFromName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发起用户名
       * </pre>
       *
       * <code>string fromName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromName() {
        
        fromName_ = getDefaultInstance().getFromName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发起用户名
       * </pre>
       *
       * <code>string fromName = 2;</code>
       * @param value The bytes for fromName to set.
       * @return This builder for chaining.
       */
      public Builder setFromNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromAvatar_ = "";
      /**
       * <pre>
       *发起方头像
       * </pre>
       *
       * <code>string fromAvatar = 3;</code>
       * @return The fromAvatar.
       */
      public java.lang.String getFromAvatar() {
        java.lang.Object ref = fromAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发起方头像
       * </pre>
       *
       * <code>string fromAvatar = 3;</code>
       * @return The bytes for fromAvatar.
       */
      public com.google.protobuf.ByteString
          getFromAvatarBytes() {
        java.lang.Object ref = fromAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发起方头像
       * </pre>
       *
       * <code>string fromAvatar = 3;</code>
       * @param value The fromAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setFromAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发起方头像
       * </pre>
       *
       * <code>string fromAvatar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromAvatar() {
        
        fromAvatar_ = getDefaultInstance().getFromAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发起方头像
       * </pre>
       *
       * <code>string fromAvatar = 3;</code>
       * @param value The bytes for fromAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setFromAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromAvatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toPhone_ = "";
      /**
       * <pre>
       *接收方方手机号
       * </pre>
       *
       * <code>string toPhone = 4;</code>
       * @return The toPhone.
       */
      public java.lang.String getToPhone() {
        java.lang.Object ref = toPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收方方手机号
       * </pre>
       *
       * <code>string toPhone = 4;</code>
       * @return The bytes for toPhone.
       */
      public com.google.protobuf.ByteString
          getToPhoneBytes() {
        java.lang.Object ref = toPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收方方手机号
       * </pre>
       *
       * <code>string toPhone = 4;</code>
       * @param value The toPhone to set.
       * @return This builder for chaining.
       */
      public Builder setToPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方方手机号
       * </pre>
       *
       * <code>string toPhone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToPhone() {
        
        toPhone_ = getDefaultInstance().getToPhone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方方手机号
       * </pre>
       *
       * <code>string toPhone = 4;</code>
       * @param value The bytes for toPhone to set.
       * @return This builder for chaining.
       */
      public Builder setToPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toName_ = "";
      /**
       * <pre>
       *接收方用户名
       * </pre>
       *
       * <code>string toName = 5;</code>
       * @return The toName.
       */
      public java.lang.String getToName() {
        java.lang.Object ref = toName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收方用户名
       * </pre>
       *
       * <code>string toName = 5;</code>
       * @return The bytes for toName.
       */
      public com.google.protobuf.ByteString
          getToNameBytes() {
        java.lang.Object ref = toName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收方用户名
       * </pre>
       *
       * <code>string toName = 5;</code>
       * @param value The toName to set.
       * @return This builder for chaining.
       */
      public Builder setToName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方用户名
       * </pre>
       *
       * <code>string toName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearToName() {
        
        toName_ = getDefaultInstance().getToName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方用户名
       * </pre>
       *
       * <code>string toName = 5;</code>
       * @param value The bytes for toName to set.
       * @return This builder for chaining.
       */
      public Builder setToNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toAvatar_ = "";
      /**
       * <pre>
       *接收方方头像
       * </pre>
       *
       * <code>string toAvatar = 6;</code>
       * @return The toAvatar.
       */
      public java.lang.String getToAvatar() {
        java.lang.Object ref = toAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收方方头像
       * </pre>
       *
       * <code>string toAvatar = 6;</code>
       * @return The bytes for toAvatar.
       */
      public com.google.protobuf.ByteString
          getToAvatarBytes() {
        java.lang.Object ref = toAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收方方头像
       * </pre>
       *
       * <code>string toAvatar = 6;</code>
       * @param value The toAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setToAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方方头像
       * </pre>
       *
       * <code>string toAvatar = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearToAvatar() {
        
        toAvatar_ = getDefaultInstance().getToAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收方方头像
       * </pre>
       *
       * <code>string toAvatar = 6;</code>
       * @param value The bytes for toAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setToAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAvatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <pre>
       *添加原因
       * </pre>
       *
       * <code>string reason = 7;</code>
       * @return The reason.
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *添加原因
       * </pre>
       *
       * <code>string reason = 7;</code>
       * @return The bytes for reason.
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *添加原因
       * </pre>
       *
       * <code>string reason = 7;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *添加原因
       * </pre>
       *
       * <code>string reason = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *添加原因
       * </pre>
       *
       * <code>string reason = 7;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       *邀请状态，新的邀请，邀请被接收，邀请被拒绝
       * </pre>
       *
       * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       *邀请状态，新的邀请，邀请被接收，邀请被拒绝
       * </pre>
       *
       * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *邀请状态，新的邀请，邀请被接收，邀请被拒绝
       * </pre>
       *
       * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus result = com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus.valueOf(status_);
        return result == null ? com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *邀请状态，新的邀请，邀请被接收，邀请被拒绝
       * </pre>
       *
       * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage.InvitationStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *邀请状态，新的邀请，邀请被接收，邀请被拒绝
       * </pre>
       *
       * <code>.ContactAddNoticeMessage.InvitationStatus status = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ContactAddNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:ContactAddNoticeMessage)
    private static final com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage();
    }

    public static com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactAddNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<ContactAddNoticeMessage>() {
      @java.lang.Override
      public ContactAddNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactAddNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactAddNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactAddNoticeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tingyu.venus.netty.protobuf.ContactAddNotice.ContactAddNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContactAddNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContactAddNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AddContactNotice.proto\"\232\002\n\027ContactAddN" +
      "oticeMessage\022\021\n\tfromPhone\030\001 \001(\t\022\020\n\010fromN" +
      "ame\030\002 \001(\t\022\022\n\nfromAvatar\030\003 \001(\t\022\017\n\007toPhone" +
      "\030\004 \001(\t\022\016\n\006toName\030\005 \001(\t\022\020\n\010toAvatar\030\006 \001(\t" +
      "\022\016\n\006reason\030\007 \001(\t\0229\n\006status\030\010 \001(\0162).Conta" +
      "ctAddNoticeMessage.InvitationStatus\"H\n\020I" +
      "nvitationStatus\022\016\n\nINVITE_NEW\020\000\022\021\n\rINVIT" +
      "E_ACCEPT\020\001\022\021\n\rINVITE_REJECT\020\002B5\n\037com.tin" +
      "gyu.venus.netty.protobufB\020ContactAddNoti" +
      "ceH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ContactAddNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ContactAddNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContactAddNoticeMessage_descriptor,
        new java.lang.String[] { "FromPhone", "FromName", "FromAvatar", "ToPhone", "ToName", "ToAvatar", "Reason", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
