// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupChatCreateNotice.proto

package com.tingyu.venus.netty.protobuf;

public final class GroupChatCreateNotice {
  private GroupChatCreateNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupChatCreateNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GroupChatCreateNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息ID  
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The groupId.
     */
    java.lang.String getGroupId();
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string groupName = 3;</code>
     * @return The groupName.
     */
    java.lang.String getGroupName();
    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string groupName = 3;</code>
     * @return The bytes for groupName.
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>string createId = 4;</code>
     * @return The createId.
     */
    java.lang.String getCreateId();
    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>string createId = 4;</code>
     * @return The bytes for createId.
     */
    com.google.protobuf.ByteString
        getCreateIdBytes();

    /**
     * <pre>
     *多个群成员用逗号分隔
     * </pre>
     *
     * <code>string memberIds = 5;</code>
     * @return The memberIds.
     */
    java.lang.String getMemberIds();
    /**
     * <pre>
     *多个群成员用逗号分隔
     * </pre>
     *
     * <code>string memberIds = 5;</code>
     * @return The bytes for memberIds.
     */
    com.google.protobuf.ByteString
        getMemberIdsBytes();

    /**
     * <pre>
     * 群公告
     * </pre>
     *
     * <code>string notice = 6;</code>
     * @return The notice.
     */
    java.lang.String getNotice();
    /**
     * <pre>
     * 群公告
     * </pre>
     *
     * <code>string notice = 6;</code>
     * @return The bytes for notice.
     */
    com.google.protobuf.ByteString
        getNoticeBytes();

    /**
     * <pre>
     *群备注
     * </pre>
     *
     * <code>string remark = 7;</code>
     * @return The remark.
     */
    java.lang.String getRemark();
    /**
     * <pre>
     *群备注
     * </pre>
     *
     * <code>string remark = 7;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code GroupChatCreateNoticeMessage}
   */
  public static final class GroupChatCreateNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GroupChatCreateNoticeMessage)
      GroupChatCreateNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupChatCreateNoticeMessage.newBuilder() to construct.
    private GroupChatCreateNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupChatCreateNoticeMessage() {
      groupId_ = "";
      groupName_ = "";
      createId_ = "";
      memberIds_ = "";
      notice_ = "";
      remark_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupChatCreateNoticeMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupChatCreateNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              groupName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              createId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              memberIds_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              notice_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.internal_static_GroupChatCreateNoticeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.internal_static_GroupChatCreateNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.class, com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *消息ID  
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object groupId_;
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The bytes for groupId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object groupName_;
    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string groupName = 3;</code>
     * @return The groupName.
     */
    @java.lang.Override
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string groupName = 3;</code>
     * @return The bytes for groupName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEID_FIELD_NUMBER = 4;
    private volatile java.lang.Object createId_;
    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>string createId = 4;</code>
     * @return The createId.
     */
    @java.lang.Override
    public java.lang.String getCreateId() {
      java.lang.Object ref = createId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>string createId = 4;</code>
     * @return The bytes for createId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreateIdBytes() {
      java.lang.Object ref = createId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERIDS_FIELD_NUMBER = 5;
    private volatile java.lang.Object memberIds_;
    /**
     * <pre>
     *多个群成员用逗号分隔
     * </pre>
     *
     * <code>string memberIds = 5;</code>
     * @return The memberIds.
     */
    @java.lang.Override
    public java.lang.String getMemberIds() {
      java.lang.Object ref = memberIds_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memberIds_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *多个群成员用逗号分隔
     * </pre>
     *
     * <code>string memberIds = 5;</code>
     * @return The bytes for memberIds.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberIdsBytes() {
      java.lang.Object ref = memberIds_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTICE_FIELD_NUMBER = 6;
    private volatile java.lang.Object notice_;
    /**
     * <pre>
     * 群公告
     * </pre>
     *
     * <code>string notice = 6;</code>
     * @return The notice.
     */
    @java.lang.Override
    public java.lang.String getNotice() {
      java.lang.Object ref = notice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notice_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 群公告
     * </pre>
     *
     * <code>string notice = 6;</code>
     * @return The bytes for notice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNoticeBytes() {
      java.lang.Object ref = notice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 7;
    private volatile java.lang.Object remark_;
    /**
     * <pre>
     *群备注
     * </pre>
     *
     * <code>string remark = 7;</code>
     * @return The remark.
     */
    @java.lang.Override
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群备注
     * </pre>
     *
     * <code>string remark = 7;</code>
     * @return The bytes for remark.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupId_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, groupName_);
      }
      if (!getCreateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, createId_);
      }
      if (!getMemberIdsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, memberIds_);
      }
      if (!getNoticeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, notice_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, remark_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupId_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, groupName_);
      }
      if (!getCreateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, createId_);
      }
      if (!getMemberIdsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, memberIds_);
      }
      if (!getNoticeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, notice_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, remark_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage)) {
        return super.equals(obj);
      }
      com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage other = (com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (!getGroupName()
          .equals(other.getGroupName())) return false;
      if (!getCreateId()
          .equals(other.getCreateId())) return false;
      if (!getMemberIds()
          .equals(other.getMemberIds())) return false;
      if (!getNotice()
          .equals(other.getNotice())) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGroupName().hashCode();
      hash = (37 * hash) + CREATEID_FIELD_NUMBER;
      hash = (53 * hash) + getCreateId().hashCode();
      hash = (37 * hash) + MEMBERIDS_FIELD_NUMBER;
      hash = (53 * hash) + getMemberIds().hashCode();
      hash = (37 * hash) + NOTICE_FIELD_NUMBER;
      hash = (53 * hash) + getNotice().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GroupChatCreateNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GroupChatCreateNoticeMessage)
        com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.internal_static_GroupChatCreateNoticeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.internal_static_GroupChatCreateNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.class, com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.Builder.class);
      }

      // Construct using com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        groupId_ = "";

        groupName_ = "";

        createId_ = "";

        memberIds_ = "";

        notice_ = "";

        remark_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.internal_static_GroupChatCreateNoticeMessage_descriptor;
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage getDefaultInstanceForType() {
        return com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage build() {
        com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage buildPartial() {
        com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage result = new com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage(this);
        result.id_ = id_;
        result.groupId_ = groupId_;
        result.groupName_ = groupName_;
        result.createId_ = createId_;
        result.memberIds_ = memberIds_;
        result.notice_ = notice_;
        result.remark_ = remark_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage) {
          return mergeFrom((com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage other) {
        if (other == com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (!other.getGroupName().isEmpty()) {
          groupName_ = other.groupName_;
          onChanged();
        }
        if (!other.getCreateId().isEmpty()) {
          createId_ = other.createId_;
          onChanged();
        }
        if (!other.getMemberIds().isEmpty()) {
          memberIds_ = other.memberIds_;
          onChanged();
        }
        if (!other.getNotice().isEmpty()) {
          notice_ = other.notice_;
          onChanged();
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息ID  
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息ID  
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID  
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @return The groupId.
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupName_ = "";
      /**
       * <pre>
       *群名称
       * </pre>
       *
       * <code>string groupName = 3;</code>
       * @return The groupName.
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群名称
       * </pre>
       *
       * <code>string groupName = 3;</code>
       * @return The bytes for groupName.
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群名称
       * </pre>
       *
       * <code>string groupName = 3;</code>
       * @param value The groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群名称
       * </pre>
       *
       * <code>string groupName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupName() {
        
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群名称
       * </pre>
       *
       * <code>string groupName = 3;</code>
       * @param value The bytes for groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createId_ = "";
      /**
       * <pre>
       *群主ID
       * </pre>
       *
       * <code>string createId = 4;</code>
       * @return The createId.
       */
      public java.lang.String getCreateId() {
        java.lang.Object ref = createId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群主ID
       * </pre>
       *
       * <code>string createId = 4;</code>
       * @return The bytes for createId.
       */
      public com.google.protobuf.ByteString
          getCreateIdBytes() {
        java.lang.Object ref = createId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群主ID
       * </pre>
       *
       * <code>string createId = 4;</code>
       * @param value The createId to set.
       * @return This builder for chaining.
       */
      public Builder setCreateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群主ID
       * </pre>
       *
       * <code>string createId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateId() {
        
        createId_ = getDefaultInstance().getCreateId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群主ID
       * </pre>
       *
       * <code>string createId = 4;</code>
       * @param value The bytes for createId to set.
       * @return This builder for chaining.
       */
      public Builder setCreateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object memberIds_ = "";
      /**
       * <pre>
       *多个群成员用逗号分隔
       * </pre>
       *
       * <code>string memberIds = 5;</code>
       * @return The memberIds.
       */
      public java.lang.String getMemberIds() {
        java.lang.Object ref = memberIds_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memberIds_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *多个群成员用逗号分隔
       * </pre>
       *
       * <code>string memberIds = 5;</code>
       * @return The bytes for memberIds.
       */
      public com.google.protobuf.ByteString
          getMemberIdsBytes() {
        java.lang.Object ref = memberIds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memberIds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *多个群成员用逗号分隔
       * </pre>
       *
       * <code>string memberIds = 5;</code>
       * @param value The memberIds to set.
       * @return This builder for chaining.
       */
      public Builder setMemberIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memberIds_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *多个群成员用逗号分隔
       * </pre>
       *
       * <code>string memberIds = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberIds() {
        
        memberIds_ = getDefaultInstance().getMemberIds();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *多个群成员用逗号分隔
       * </pre>
       *
       * <code>string memberIds = 5;</code>
       * @param value The bytes for memberIds to set.
       * @return This builder for chaining.
       */
      public Builder setMemberIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memberIds_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object notice_ = "";
      /**
       * <pre>
       * 群公告
       * </pre>
       *
       * <code>string notice = 6;</code>
       * @return The notice.
       */
      public java.lang.String getNotice() {
        java.lang.Object ref = notice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 群公告
       * </pre>
       *
       * <code>string notice = 6;</code>
       * @return The bytes for notice.
       */
      public com.google.protobuf.ByteString
          getNoticeBytes() {
        java.lang.Object ref = notice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群公告
       * </pre>
       *
       * <code>string notice = 6;</code>
       * @param value The notice to set.
       * @return This builder for chaining.
       */
      public Builder setNotice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        notice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群公告
       * </pre>
       *
       * <code>string notice = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNotice() {
        
        notice_ = getDefaultInstance().getNotice();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群公告
       * </pre>
       *
       * <code>string notice = 6;</code>
       * @param value The bytes for notice to set.
       * @return This builder for chaining.
       */
      public Builder setNoticeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        notice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <pre>
       *群备注
       * </pre>
       *
       * <code>string remark = 7;</code>
       * @return The remark.
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群备注
       * </pre>
       *
       * <code>string remark = 7;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群备注
       * </pre>
       *
       * <code>string remark = 7;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群备注
       * </pre>
       *
       * <code>string remark = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群备注
       * </pre>
       *
       * <code>string remark = 7;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GroupChatCreateNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:GroupChatCreateNoticeMessage)
    private static final com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage();
    }

    public static com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupChatCreateNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<GroupChatCreateNoticeMessage>() {
      @java.lang.Override
      public GroupChatCreateNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupChatCreateNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupChatCreateNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupChatCreateNoticeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tingyu.venus.netty.protobuf.GroupChatCreateNotice.GroupChatCreateNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupChatCreateNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupChatCreateNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033GroupChatCreateNotice.proto\"\223\001\n\034GroupC" +
      "hatCreateNoticeMessage\022\n\n\002id\030\001 \001(\003\022\017\n\007gr" +
      "oupId\030\002 \001(\t\022\021\n\tgroupName\030\003 \001(\t\022\020\n\010create" +
      "Id\030\004 \001(\t\022\021\n\tmemberIds\030\005 \001(\t\022\016\n\006notice\030\006 " +
      "\001(\t\022\016\n\006remark\030\007 \001(\tB:\n\037com.tingyu.venus." +
      "netty.protobufB\025GroupChatCreateNoticeH\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GroupChatCreateNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GroupChatCreateNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupChatCreateNoticeMessage_descriptor,
        new java.lang.String[] { "Id", "GroupId", "GroupName", "CreateId", "MemberIds", "Notice", "Remark", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
