// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserOnlineNotice.proto

package com.tingyu.venus.netty.protobuf;

public final class UserOnlineNotice {
  private UserOnlineNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOnlineNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserOnlineNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userPhone = 1;</code>
     * @return The userPhone.
     */
    java.lang.String getUserPhone();
    /**
     * <code>string userPhone = 1;</code>
     * @return The bytes for userPhone.
     */
    com.google.protobuf.ByteString
        getUserPhoneBytes();
  }
  /**
   * Protobuf type {@code UserOnlineNoticeMessage}
   */
  public static final class UserOnlineNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserOnlineNoticeMessage)
      UserOnlineNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserOnlineNoticeMessage.newBuilder() to construct.
    private UserOnlineNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserOnlineNoticeMessage() {
      userPhone_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserOnlineNoticeMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserOnlineNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userPhone_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tingyu.venus.netty.protobuf.UserOnlineNotice.internal_static_UserOnlineNoticeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tingyu.venus.netty.protobuf.UserOnlineNotice.internal_static_UserOnlineNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.class, com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.Builder.class);
    }

    public static final int USERPHONE_FIELD_NUMBER = 1;
    private volatile java.lang.Object userPhone_;
    /**
     * <code>string userPhone = 1;</code>
     * @return The userPhone.
     */
    @java.lang.Override
    public java.lang.String getUserPhone() {
      java.lang.Object ref = userPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string userPhone = 1;</code>
     * @return The bytes for userPhone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserPhoneBytes() {
      java.lang.Object ref = userPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userPhone_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userPhone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage)) {
        return super.equals(obj);
      }
      com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage other = (com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage) obj;

      if (!getUserPhone()
          .equals(other.getUserPhone())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getUserPhone().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserOnlineNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserOnlineNoticeMessage)
        com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tingyu.venus.netty.protobuf.UserOnlineNotice.internal_static_UserOnlineNoticeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tingyu.venus.netty.protobuf.UserOnlineNotice.internal_static_UserOnlineNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.class, com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.Builder.class);
      }

      // Construct using com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userPhone_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tingyu.venus.netty.protobuf.UserOnlineNotice.internal_static_UserOnlineNoticeMessage_descriptor;
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage getDefaultInstanceForType() {
        return com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage build() {
        com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage buildPartial() {
        com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage result = new com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage(this);
        result.userPhone_ = userPhone_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage) {
          return mergeFrom((com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage other) {
        if (other == com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage.getDefaultInstance()) return this;
        if (!other.getUserPhone().isEmpty()) {
          userPhone_ = other.userPhone_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userPhone_ = "";
      /**
       * <code>string userPhone = 1;</code>
       * @return The userPhone.
       */
      public java.lang.String getUserPhone() {
        java.lang.Object ref = userPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userPhone = 1;</code>
       * @return The bytes for userPhone.
       */
      public com.google.protobuf.ByteString
          getUserPhoneBytes() {
        java.lang.Object ref = userPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userPhone = 1;</code>
       * @param value The userPhone to set.
       * @return This builder for chaining.
       */
      public Builder setUserPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userPhone = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserPhone() {
        
        userPhone_ = getDefaultInstance().getUserPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string userPhone = 1;</code>
       * @param value The bytes for userPhone to set.
       * @return This builder for chaining.
       */
      public Builder setUserPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPhone_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserOnlineNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:UserOnlineNoticeMessage)
    private static final com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage();
    }

    public static com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserOnlineNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<UserOnlineNoticeMessage>() {
      @java.lang.Override
      public UserOnlineNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserOnlineNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserOnlineNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserOnlineNoticeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tingyu.venus.netty.protobuf.UserOnlineNotice.UserOnlineNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserOnlineNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserOnlineNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026UserOnlineNotice.proto\",\n\027UserOnlineNo" +
      "ticeMessage\022\021\n\tuserPhone\030\001 \001(\tB3\n\037com.ti" +
      "ngyu.venus.netty.protobufB\020UserOnlineNot" +
      "iceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserOnlineNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserOnlineNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserOnlineNoticeMessage_descriptor,
        new java.lang.String[] { "UserPhone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
